### ISSUE TITLE
When can we expect v0.4?

### ISSUE THREAD

**Issue by kjeremy** [couchbaselabs/couchbase-rs#37]

**Comment by daschl** [comment]
Hi @kjeremy ,

we are currently working on a 1.0.0-alpha.1 which should hopefully be released in the next few weeks and have a new API which is built alongside our new SDK series "dubbed sdk 3.0". 

Would love - if you are still interested - to give it a spin? You can fetch it from master as well, the examples dir has some code already.

I'll close this one out since 0.4 will become 1.0.0-alpha.1
