### ISSUE TITLE
Library include connection pool ?

### ISSUE THREAD

**Issue by esoftcard** [couchbaselabs/couchbase-rs#52]
Does the library include connection pool inside ?

**Comment by adamhjk** [comment]
It does not.

**Comment by esoftcard** [comment]
I see that it is a developing driver for rust , why it hasn't been
completed ?

**Comment by adamhjk** [comment]
A lot of churn in the rust async ecosystem is the main reason. Even so,
idiomatic rust would put connection pooling outside the driver.

**Comment by daschl** [comment]
@esoftcard while everything is in flux, there is actually no need for connection pooling. the stack is completely asynchronous and also more complex than traditional rdbms drivers. (We are maintaining sockets and pools of them inside the SDK, because we also need to handle adding and removing of nodes etc.)..

So bottom line is there is no need for a connection pool on top of the couchbase SDK (this is also true for i.e. the java sdk, so its not rust specific)
